services:
  registry:
    image: registry:latest
    restart: always
    ports:
      - "5005:5005"
    volumes:
      - /home/dima/jenkins/registry:/var/lib/registry
    hostname: registry;
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5005
  jenkins:
    image: jenkins/jenkins:jdk21
    hostname: jenkins
    privileged: true
    restart: always
    user: root
    environment:
      - JAVA_OPTS="-Dhudsson.model.DownloadService.noSugnatureCheck=true"
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /home/dima/jenkins_otus/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  nginx:
    image: nginx:latest
    hostname: nginx
    restart: always
    privileged: true
    depends_on:
      - jenkins
    ports:
      - "80:80"
    volumes:
      - /home/dima/jenkins/nginx/:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime